# Generated by Django 4.1.6 on 2023-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbimage',
            field=models.ImageField(default='', upload_to='thumbimage/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
